### ISSUE TITLE
Wix checkout and cart sidebar not translated

### ISSUE THREAD

**Issue by remyberda** [weglot/technology-rules#10]
Sur ce site https://tw.vegapuff.com/ , deux choses ne sont pas traduites:
- Le volet cart 
- Le checkout
Ca semble être des custom définitions qui manquent. Il faudrait les trouver puis les ajouter ici pour que tous le monde puisse en bénéficier
<img width="1176" alt="Capture d’écran 2021-10-13 à 16 56 26" src="https://user-images.githubusercontent.com/22366468/137158924-505ca148-401d-4f46-aa13-25c7dff9b785.png">

<img width="1038" alt="Capture d’écran 2021-10-13 à 16 55 51" src="https://user-images.githubusercontent.com/22366468/137158934-a6633d8a-38eb-4766-b906-c736904ffb2e.png">

**Comment by nico2che** [comment]
outdated
